import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * docs-integrator: `main` — Sidebar Configuration
 *
 * `main` carries no real product content (see MAINTENANCE.md's "What
 * `main` is for") -- docs/ here is mostly a placeholder scaffold
 * (Section 1 with a couple of sample sub-sections, Section 2
 * demonstrating the sidebar separator convention, Icons, Homepage,
 * Workflows) demonstrating the doc structure conventions from
 * CONTRIBUTING.md, not a real documentation set. Platform Overview,
 * Get Started, Guides, and Reference are the exception: copied from (or
 * sample-filled in the same shape as) saas's real structure, since
 * every product branch needs something at those four paths.
 *
 * Autogenerated from the docs/ folder structure, same as every product
 * branch (saas, wso2-integrator, wso2-connectors) -- this file used to
 * be a large hand-maintained doc-id list instead, which is exactly what
 * produces stale-reference bugs during any restructure. Each folder
 * carries an explicit `_category_.json` fixing its label and position;
 * each doc sets its own `sidebar_position` rather than relying on the
 * alphabetical fallback.
 */
const sidebars: SidebarsConfig = {
  mainSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
