const path = require('path');
const fs = require('fs');
const matter = require('gray-matter');
const fg = require('fast-glob');

/**
 * Generates the data behind the Guides landing page's search + card grid
 * (src/components/GuidesCatalog) directly from each guide doc's own
 * frontmatter, instead of a hand-maintained array that has to be kept in
 * sync by hand every time a guide is added, renamed, or moved -- the
 * same class of stale-reference bug this repo's fully-autogenerated
 * sidebar (see sidebars.ts) already exists to avoid.
 *
 * Reads every *.md file directly under docs/guides/how-to-guides/ and
 * docs/guides/business-use-cases/ (skipping each folder's own
 * `<folder>/<folder>.md` index page) and requires three frontmatter
 * fields on each:
 *   - `slug`         (already required sitewide -- used as the card's href)
 *   - `card_icon`    a PaletteIconName (src/components/PaletteIcon)
 *   - `card_summary` a short one-line blurb for the card body
 * `title` (also already required sitewide) is reused as the card title.
 * A doc missing any of these fails the build with a specific, actionable
 * error rather than silently rendering an incomplete or generic card.
 *
 * `card_keywords` (a string array, same shape as the sitewide `keywords`
 * field) is OPTIONAL -- extra search terms for GuidesCatalog's search
 * box that aren't necessarily in the title or summary (e.g. "chatbot",
 * "mssql", "vector database"). Skip it for guides where the title and
 * summary already cover the terms someone would search for; add it
 * where they don't.
 *
 * The two folders are two genuinely different kinds of guide, not just
 * two piles of content: `how-to-guides/` demonstrates one integration
 * capability or pattern in the abstract (an agent, a connector, an
 * event listener), while `business-use-cases/` solves a concrete,
 * end-to-end problem for a named business function (HR, IT support,
 * customer care, procurement). Which folder a new guide belongs in is
 * a judgment call on that basis, not on topic (AI vs. not) or on where
 * its content originally came from.
 *
 * Plain JS, not TS: local plugins referenced by string path in the
 * `plugins` array (docusaurus.config.ts) are resolved with a plain
 * Node `require()`, which doesn't understand TypeScript syntax -- only
 * docusaurus.config.ts itself gets TS support, via a separate loader.
 * See src/components/GuidesCatalog for this plugin's own local copy of
 * the GuideCardData/GuideCategory shape (TS types can't be imported
 * from a .js file in a meaningful way, so it's redeclared there).
 *
 * Exposed to the client via Docusaurus's global-data mechanism
 * (setGlobalData / usePluginData('guides-catalog-plugin')) -- see
 * GuidesCatalog for the consumer side.
 */
const CATEGORY_DIRS = [
  { dir: 'how-to-guides', category: 'how-to' },
  { dir: 'business-use-cases', category: 'business' },
];

const REQUIRED_FIELDS = ['title', 'slug', 'card_icon', 'card_summary'];

module.exports = function guidesCatalogPlugin(context) {
  return {
    name: 'guides-catalog-plugin',

    async loadContent() {
      const guidesRoot = path.join(context.siteDir, 'docs', 'guides');
      // sidebar_position isn't part of the data returned to the client
      // -- only used here to sort each category's cards to match the
      // order its docs already appear in the sidebar.
      const cards = [];

      for (const { dir, category } of CATEGORY_DIRS) {
        const folder = path.join(guidesRoot, dir);
        const files = await fg('*.md', { cwd: folder, absolute: true });

        for (const file of files) {
          const base = path.basename(file, '.md');
          // Skip the folder's own index page (<folder>/<folder>.md) --
          // that's the subsection landing page, not an individual guide.
          if (base === dir) continue;

          const relPath = path.relative(context.siteDir, file);
          const { data } = matter(fs.readFileSync(file, 'utf8'));

          for (const field of REQUIRED_FIELDS) {
            if (!data[field]) {
              throw new Error(
                `[guides-catalog-plugin] ${relPath} is missing "${field}" in its frontmatter -- ` +
                  'every doc under guides/how-to-guides/ or guides/business-use-cases/ needs title, ' +
                  'slug, card_icon (a PaletteIconName from src/components/PaletteIcon), and ' +
                  'card_summary (a short one-line card description) so its guide card can be built.',
              );
            }
          }

          cards.push({
            title: data.title,
            href: data.slug,
            icon: data.card_icon,
            summary: data.card_summary,
            keywords: data.card_keywords ?? [],
            category,
            position: data.sidebar_position ?? Number.MAX_SAFE_INTEGER,
          });
        }
      }

      cards.sort((a, b) => a.position - b.position);
      return cards.map(({ position, ...card }) => card);
    },

    async contentLoaded({ content, actions }) {
      actions.setGlobalData(content);
    },
  };
};
