/**
 * Full replacement of @theme-original/DocSidebarItems (not a wrap -- the
 * stock component maps `items` straight into <DocSidebarItem>, with no
 * hook to inject anything between them).
 *
 * Adds one thing on top of stock behavior: an item whose `customProps`
 * sets `separatorBefore: "Label"` gets a non-clickable section-label
 * rendered immediately before it -- set via a category's
 * `_category_.json` (`customProps: {...}`) or a flat doc's own
 * frontmatter (`sidebar_custom_props: {...}`), same field name either
 * way. Used by manage/'s three-tier grouping (see
 * manage/managed-databases-and-caches.md's frontmatter and
 * manage/billing/_category_.json) so the tiers read as visually
 * separate groups WITHOUT hand-maintaining a sidebar entry for every
 * product area -- `{type: 'autogenerated', dirName: '.'}` in sidebars.ts
 * still does 100% of the ordering (via each item's own `position`); this
 * only adds a label, it never overrides structure or order.
 *
 * Original: node_modules/@docusaurus/theme-classic/lib/theme/DocSidebarItems/index.js
 * Keep this file in sync if you bump the @docusaurus/theme-classic major version.
 */
import React, { memo, type ReactNode } from 'react';
import {
  DocSidebarItemsExpandedStateProvider,
  useVisibleSidebarItems,
} from '@docusaurus/plugin-content-docs/client';
import DocSidebarItem from '@theme/DocSidebarItem';
import type { Props } from '@theme/DocSidebarItems';

import styles from './styles.module.css';

function separatorLabelOf(item: Props['items'][number]): string | undefined {
  const customProps = (item as { customProps?: Record<string, unknown> }).customProps;
  const label = customProps?.separatorBefore;
  return typeof label === 'string' ? label : undefined;
}

function DocSidebarItems({ items, ...props }: Props): ReactNode {
  const visibleItems = useVisibleSidebarItems(items, props.activePath);
  return (
    <DocSidebarItemsExpandedStateProvider>
      {visibleItems.map((item, index) => {
        const separatorLabel = separatorLabelOf(item);
        return (
          <React.Fragment key={index}>
            {separatorLabel && (
              <div className={styles.separator} role="separator" aria-label={separatorLabel}>
                {separatorLabel}
              </div>
            )}
            <DocSidebarItem item={item} index={index} {...props} />
          </React.Fragment>
        );
      })}
    </DocSidebarItemsExpandedStateProvider>
  );
}

export default memo(DocSidebarItems);
